---
- name: WME Studio Workspace/AppDeploy instances setup
  hosts: all
  become: yes
  any_errors_fatal: true
  strategy: debug
  vars:
    rhel_os_version: "{{ operating_version }}"
    custom_user_setup: "{{ setup_with_custom_sshkeys }}"
    customuser_name: "{{ internal_user_for_wavemaker }}"
    rhel_os_user_name: "{{ os_user_name }}"
    debian_os_user_name: "{{ os_user_name }}"
    user_pemfile: "{{ internal_user_ssh_key_for_wavemaker }}"
    wme_version: "{{ wme_platform_version }}"
  

  tasks:
  # aws instance operations(volume mounting)  
  - name: Finding volume device name for data volume
    shell: lsblk -o NAME,SIZE,FSTYPE -dsn | awk '$3 == "" && $2 == "150G" {print $1}'
    register: data_device

  - name: creating file system for volumes
    community.general.filesystem:
      fstype: ext4
      dev: "{{ item }}"
    with_items:
      - /dev/{{ data_device.stdout }}
    ignore_errors: True
  
  - name: Create a directory data
    file:
      path: "{{ item }}"
      state: directory
      mode: '0755'
    with_items:
      - /data

  - name: mounting data volume for volumes
    mount:
      path: /data
      src: /dev/{{ data_device.stdout }}
      fstype: ext4
      state: mounted
      
  - name: update cache for ubuntu
    apt:
      update_cache: yes
    when: ansible_os_family == "Debian"

  - name: update cache for RHEL
    yum:
      name: "*"
      state: latest
    when: ansible_os_family == "RedHat"

 # custom user creation
  - name: adding custom user
    user:
      name: "{{ customuser_name }}"
      shell: /bin/bash
    when: 
      - custom_user_setup == "yes"

  - name: creating .ssh folder for custom user
    file:
      path: /home/{{ customuser_name }}/.ssh/
      state: directory
      mode: '0755'
    when: 
      - custom_user_setup == "yes"

  - name: docker installation for custom user in ubuntu
    shell: |
      apt-get install apt-transport-https
      curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable" > /etc/apt/sources.list.d/docker.list
      apt-get update  
      apt-get install iptables ca-certificates
    when: 
      - ansible_os_family == "Debian"
      - custom_user_setup == "yes"

  - name: Docker 19.03.13~3-0~ubuntu-xenial installation in Ubuntu
    shell: |
      apt-get install docker-ce=5:19.03.13~3-0~ubuntu-xenial docker-ce-cli=5:19.03.13~3-0~ubuntu-xenial containerd.io -y
    when:
      - ansible_os_family == "Debian"
      - custom_user_setup == "yes"
      - wme_version == "10.6.0" or wme_version == "10.6.1"

  - name: Docker 18.06 installation in ubuntu
    shell: |
      apt-get install docker-ce=18.06.2~ce~3-0~ubuntu -y
    when:
      - ansible_os_family == "Debian"
      - custom_user_setup == "yes"
      - wme_version == "10.5.3" or wme_version == "10.5.6"


  - name: creating docker service directory in ubuntu for custom user setup
    file:
      path: /etc/systemd/system/docker.service.d/
      state: directory
      mode: '0755'
    when: 
        - ansible_os_family == "Debian"
        - custom_user_setup == "yes"

  - name: finding pemfile name
    shell: echo {{ user_pemfile }} | awk -F/ '{print $NF}'
    register: pemfile_name
    when: 
      - custom_user_setup == "yes"
    
  - name: adding permissions to custom user in ubuntu
    shell: |
      cp /home/{{ debian_os_user_name }}/{{ pemfile_name.stdout }} /home/{{ customuser_name }}/ 
      ssh-keygen -y -f /home/{{ customuser_name }}/{{ pemfile_name.stdout }} > /home/{{ customuser_name }}/.ssh/authorized_keys
      rm -f /home/{{ debian_os_user_name }}/{{ pemfile_name.stdout }}
      chown -R {{ customuser_name }}:{{ customuser_name }} /home/{{ customuser_name }}/
      chown -R {{ customuser_name }}:{{ customuser_name }} /data
      chown -R {{ customuser_name }}:{{ customuser_name }} /etc/systemd/system/docker.service.d/
      usermod -aG docker {{ customuser_name }}
      echo "%{{ customuser_name }} ALL=NOPASSWD: /bin/systemctl restart docker.service,/bin/systemctl daemon-reload,/sbin/iptables" > /etc/sudoers.d/{{ customuser_name }}
    when: 
      - ansible_os_family == "Debian"
      - custom_user_setup == "yes"
    ignore_errors: True

  
  # installing pip3 and wget
  - name: installing pip3 and wget
    package:
      name: 
        - python3-pip
        - wget
      state: present

  - name: providing functionality pip using pip3
    alternatives:
      name: pip
      link: /usr/bin/pip
      path: /usr/bin/pip3
      priority: 1
    when: ansible_os_family == "RedHat"


# RHEL instance prerequisites installing and IPv6 disable
  - name: checking IPV6 address
    shell: ip addr show | grep net6
    register: ipv6_addr_checking
    ignore_errors: True

  - name: setup IPV6 validation variable
    set_fact:
      ipv6_address: "{{ ipv6_addr_checking.stdout }}"

  - name: ipv6 disable in RHEL
    lineinfile:
      path: /etc/default/grub
      regexp: "^GRUB_CMDLINE_LINUX="
      line: 'GRUB_CMDLINE_LINUX="ipv6.disable=1 console=ttyS0,115200n8 console=tty0 net.ifnames=0 rd.blacklist=nouveau nvme_core.io_timeout=4294967295 crashkernel=auto"'
    when: 
     - ansible_os_family == "RedHat"
     - ipv6_address != "" 
  
  - name: updating grub conf file in rhel for ipv6 disable
    shell: grub2-mkconfig -o /boot/grub2/grub.cfg
    when: 
     - ansible_os_family == "RedHat"
     - ipv6_address != ""
  

  - name: reboot the system for updating the grub configurations
    reboot:
    when: 
     - ansible_os_family == "RedHat"
     - ipv6_address != ""
  
  - name: installing SELinux container on RHEL 7 form remote url
    yum:
      name: http://ftp.riken.jp/Linux/cern/centos/7/extras/x86_64/Packages/container-selinux-2.10-2.el7.noarch.rpm
      state: present
    when: 
      - ansible_os_family == "RedHat"
      - rhel_os_version == "7"

  
  - name: installing Docker 19.03.13 and python3 in rhel
    yum:
      name: 
      - https://download.docker.com/linux/centos/8/x86_64/stable/Packages/docker-ce-cli-19.03.13-3.el8.x86_64.rpm
      - https://download.docker.com/linux/centos/8/x86_64/stable/Packages/containerd.io-1.3.7-3.1.el8.x86_64.rpm
      - https://download.docker.com/linux/centos/8/x86_64/stable/Packages/docker-ce-19.03.13-3.el8.x86_64.rpm
      - python3
      disable_gpg_check: yes 
    when: 
      - ansible_os_family == "RedHat"
      - wme_version == "10.6.0" or wme_version == "10.6.1"

  - name: Installing Docker 18.06 and python in rhel
    yum:
      name: 
        - https://download.docker.com/linux/centos/7/x86_64/stable/Packages/docker-ce-18.06.2.ce-3.el7.x86_64.rpm
        - python3
      disable_gpg_check: yes
    when:
      - ansible_os_family == "RedHat"
      - wme_version == "10.5.3" or wme_version == "10.5.6"

  
  - name: starting Docker
    service: 
      name: docker
      state: started
      enabled: yes
    become: true
    when: ansible_os_family == "RedHat"

  - name: adding ec2 user to the docker group
    shell: usermod -aG docker {{ rhel_os_user_name }}
    when: 
     - ansible_os_family == "RedHat"
     - custom_user_setup == "no"
  

# custom user permissions in RHEL instance
  - name: adding permissions to user in RHEL
    shell: |
      cp /home/{{ rhel_os_user_name }}/{{ pemfile_name.stdout }} /home/{{ customuser_name }}/
      ssh-keygen -y -f /home/{{ customuser_name }}/{{ pemfile_name.stdout }} > /home/{{ customuser_name }}/.ssh/authorized_keys
      rm -f /home/{{ rhel_os_user_name }}/{{ pemfile_name.stdout }}
      chown -R {{ customuser_name }}:{{ customuser_name }} /home/{{ customuser_name }}/
      chown -R {{ customuser_name }}:{{ customuser_name }} /data
      usermod -aG docker {{ customuser_name }}
      chown -R {{ customuser_name }}:{{ customuser_name }} /usr/lib/systemd/system
      echo "%{{ customuser_name }} ALL=NOPASSWD: /bin/systemctl restart docker.service,/bin/systemctl daemon-reload,/usr/sbin/iptables" > /etc/sudoers.d/{{ customuser_name }}
      chown -R {{ customuser_name }}:{{ customuser_name }} /usr/lib/systemd/system/docker.service
    when: 
      - ansible_os_family == "RedHat"
      - custom_user_setup == "yes"
    ignore_errors: True